FROM postgres
RUN localedef -i de_DE -c -f UTF-8 -A /usr/share/locale/locale.alias de_DE.UTF-8
ENV LANG de_DE.utf8
COPY config/postgrest-init-db.sh /docker-entrypoint-initdb.d/
# RUN ln -s /etc/systemd/system/postgrest.service /etc/systemd/system/multi-user.target.wants/postgrest.service 
