#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE ROLE ${PGRST_ANON_ROLE} nologin;
    CREATE SCHEMA IF NOT EXISTS ${PGRST_SCHEMA};	
    GRANT USAGE ON SCHEMA ${PGRST_SCHEMA} to ${PGRST_ANON_ROLE};
    ALTER DEFAULT PRIVILEGES IN SCHEMA ${PGRST_SCHEMA} GRANT SELECT ON TABLES TO ${PGRST_ANON_ROLE};
    CREATE ROLE ${PGRST_USER} noinherit login password '${PGRST_PASSWORD}';
    GRANT ${PGRST_ANON_ROLE} TO ${PGRST_USER};
EOSQL
